package inter.sdk.banking.enums;

public enum PixStatus {
    CRIADO,
    AGUARDANDO_APROVACAO,
    APROVADO,
    REPROVADO,
    EXPIRADO,
    CANCELADO,
    FALHA,
    AGENDADO,
    PAGO,
    ENVIADO,
    CANCELADO_SEM_SALDO,
    DEBITADO,
    PARCIALMENTE_DEBITADO,
    PARCIALMENTE_PAGO,
    NAO_DEBITADO,
    AGENDAMENTO_CANCELADO,
    TRANSACAO_CRIADA,
    TRANSACAO_APROVADA,
    PIX_ENVIADO,
    PIX_PAGO
}
