package inter.sdk.billing.enums;

public enum DiscountCode {
    NAOTEMDESCONTO,
    VALORFIXODATAINFORMADA,
    PERCENTUALDATAINFORMADA,
    VALORANTECIPACAODIAUTIL,
    PERCENTUALVALORNOMINALDIACORRIDO,
    PERCENTUALVALORNOMINALDIAUTIL
}
